// list of routes that forbidden to get cached
const routesToNotCache = [
  `/account.php`,
  `/admin`,
  `/age-verification`,
  `/api/storefront`,
  '/remote/v1',
  `/cart.php`,
  `/checkout.php`,
  `/contact-us`,
  `/customer`,
  `/customer-support`,
  `/finishorder.php`,
  `/giants-club`,
  `/login-as-customer`,
  `/login.php`,
  `/manage`,
  `/manual-verification`,
  `/oauth2`,
  `/order-verification`,
  `/order.html`,
  `/robots.txt`,
  `/sitemap.xml`,
  `/subscribe`,
  `/vendors`,
  `/verification-in-progress`,
  `/wishlist`,
  '/smok-pozz-x-pods',
  '/smok-alike-pods',
  '/sicboy',
  '/medhaven-masks',
  '/king-s-crown',
  '/giantvapes.com/focus-goji-cacao-cbd-tincture',
  '/geekvape-aegis-hero',
  '/charlie-s-chalk-dust',
  '/big-willie-s',
  '/your-rewards',
];

export default routesToNotCache;
